packages:
  - "apps/*"
  - "packages/*"
  - "infrastructure/pulumi"
allowBuilds:
  '@pulumi/command': true
  '@prisma/engines': true
  argon2: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
