import { DashboardTemplate, SavedDashboard, ThemeGroup } from "./types";

export const templates: DashboardTemplate[] = [
  {
    id: "executive-overview",
    name: "Executive Overview",
    description: "Strategy KPIs for board reporting",
    widgetCount: 8,
    icon: "grid",
    iconBg: "bg-[#0f2f4f]",
  },
  {
    id: "sales-performance",
    name: "Sales Performance",
    description: "Pipeline, revenue and conversion",
    widgetCount: 6,
    icon: "trending",
    iconBg: "bg-[#2f6fed]",
  },
  {
    id: "engineering-metrics",
    name: "Engineering Metrics",
    description: "Velocity, quality and deployments",
    widgetCount: 6,
    icon: "bolt",
    iconBg: "bg-[#1fa971]",
  },
];

export const savedDashboards: SavedDashboard[] = [
  {
    id: "exec-overview-q3",
    name: "Executive Overview Q3",
    subtitle: "8 widgets · Updated 2h ago",
    description: "Strategy execution KPIs for board reporting. Updated for Q3 2025.",
    tags: ["Strategy", "Executive"],
    widgetCount: 8,
    date: "Jul 18, 2025",
    shared: true,
    updatedAt: "2h ago",
    accent: "#0f2f4f",
  },
  {
    id: "sales-performance-live",
    name: "Sales Performance",
    subtitle: "6 widgets · Updated yesterday",
    description: "Pipeline health, revenue metrics and conversion funnel.",
    tags: ["Sales", "Revenue"],
    widgetCount: 6,
    date: "Jul 15, 2025",
    shared: false,
    updatedAt: "1d ago",
    accent: "#2f6fed",
  },
  {
    id: "engineering-health",
    name: "Engineering Health",
    subtitle: "6 widgets · Updated 3d ago",
    description: "Sprint velocity, deployment frequency and quality metrics.",
    tags: ["Engineering", "DevOps"],
    widgetCount: 6,
    date: "Jul 12, 2025",
    shared: true,
    updatedAt: "3d ago",
    accent: "#1fa971",
  },
];

export const themeGroups: ThemeGroup[] = [
  {
    id: "revenue-growth",
    name: "Revenue & Growth",
    color: "#7c5cff",
    atRisk: 0,
    behind: 1,
    initiatives: [
      {
        id: "crm-platform-migration",
        name: "CRM Platform Migration",
        play: "Commercial Excellence",
        objective: "Drive Revenue Growth 40% YoY",
        status: "In Progress",
        rag: "on-track",
        stage: "Execution",
        progress: 62,
        milestonesDone: 2,
        milestonesTotal: 4,
        confidence: "Medium",
        owner: { initials: "SC", name: "Sarah Chen", color: "#f59e0b" },
        budgetSpend: 298_000,
        budgetTotal: 480_000,
        strategicWeight: 78,
        healthScore: 66,
        color: "#2f6fed",
      },
      {
        id: "apac-market-expansion",
        name: "APAC Market Expansion",
        play: "Market Expansion",
        objective: "Drive Revenue Growth 40% YoY",
        status: "Behind",
        rag: "off-track",
        stage: "Execution",
        progress: 31,
        milestonesDone: 1,
        milestonesTotal: 4,
        confidence: "Low",
        owner: { initials: "TR", name: "Tom Reeves", color: "#ef4444" },
        budgetSpend: 295_000,
        budgetTotal: 950_000,
        strategicWeight: 86,
        healthScore: 28,
        color: "#ef4444",
      },
      {
        id: "revenue-intelligence-dashboard",
        name: "Revenue Intelligence Dashboard",
        play: "Revenue Intelligence",
        objective: "Drive Revenue Growth 40% YoY",
        status: "Draft",
        rag: "draft",
        stage: "Planning",
        progress: 8,
        milestonesDone: 0,
        milestonesTotal: 3,
        confidence: "Medium",
        owner: { initials: "SC", name: "Sarah Chen", color: "#f59e0b" },
        budgetSpend: 18_000,
        budgetTotal: 220_000,
        strategicWeight: 32,
        healthScore: 22,
        color: "#f59e0b",
      },
    ],
  },
  {
    id: "customer-experience",
    name: "Customer Experience",
    color: "#0ea5e9",
    atRisk: 1,
    behind: 0,
    initiatives: [
      {
        id: "ai-powered-support-bot",
        name: "AI-Powered Support Bot",
        play: "Service Excellence",
        objective: "Reduce Response Time 50%",
        status: "In Progress",
        rag: "at-risk",
        stage: "Execution",
        progress: 44,
        milestonesDone: 2,
        milestonesTotal: 5,
        confidence: "Medium",
        owner: { initials: "JP", name: "Jordan Park", color: "#7c5cff" },
        budgetSpend: 141_000,
        budgetTotal: 320_000,
        strategicWeight: 70,
        healthScore: 62,
        color: "#7c5cff",
      },
    ],
  },
  {
    id: "operational-efficiency",
    name: "Operational Efficiency",
    color: "#1fa971",
    atRisk: 0,
    behind: 0,
    initiatives: [
      {
        id: "facilities-rightsizing",
        name: "Facilities Rightsizing",
        play: "Cost Efficiency",
        objective: "Reduce Operating Costs 15%",
        status: "On Track",
        rag: "on-track",
        stage: "Execution",
        progress: 88,
        milestonesDone: 3,
        milestonesTotal: 4,
        confidence: "High",
        owner: { initials: "MK", name: "Maya Khan", color: "#7c5cff" },
        budgetSpend: 96_000,
        budgetTotal: 140_000,
        strategicWeight: 30,
        healthScore: 84,
        color: "#f97316",
      },
    ],
  },
  {
    id: "technology-platform",
    name: "Technology & Platform",
    color: "#14b8a6",
    atRisk: 2,
    behind: 0,
    initiatives: [
      {
        id: "cloud-infrastructure-modernization",
        name: "Cloud Infrastructure Modernization",
        play: "Platform Reliability",
        objective: "Modernize Core Infrastructure",
        status: "On Track",
        rag: "on-track",
        stage: "Execution",
        progress: 55,
        milestonesDone: 3,
        milestonesTotal: 6,
        confidence: "High",
        owner: { initials: "PN", name: "Priya Nair", color: "#1fa971" },
        budgetSpend: 660_000,
        budgetTotal: 1_200_000,
        strategicWeight: 82,
        healthScore: 74,
        color: "#1fa971",
      },
      {
        id: "analytics-data-warehouse",
        name: "Analytics Data Warehouse",
        play: "Data Platform",
        objective: "Unify Reporting Infrastructure",
        status: "In Progress",
        rag: "at-risk",
        stage: "Execution",
        progress: 48,
        milestonesDone: 2,
        milestonesTotal: 5,
        confidence: "Medium",
        owner: { initials: "MW", name: "Maria Wong", color: "#7c5cff" },
        budgetSpend: 202_000,
        budgetTotal: 420_000,
        strategicWeight: 80,
        healthScore: 68,
        color: "#7c5cff",
      },
      {
        id: "enterprise-sso-rollout",
        name: "Enterprise SSO Rollout",
        play: "Security & Compliance",
        objective: "Consolidate Identity Access",
        status: "In Progress",
        rag: "at-risk",
        stage: "Planning",
        progress: 72,
        milestonesDone: 2,
        milestonesTotal: 4,
        confidence: "Medium",
        owner: { initials: "DF", name: "Dana Fields", color: "#ec4899" },
        budgetSpend: 188_000,
        budgetTotal: 400_000,
        strategicWeight: 24,
        healthScore: 80,
        color: "#ec4899",
      },
    ],
  },
];
