- sub: foo
  name: Foo
  email: foo@example.com
  email_verified: true
  aud: spm-web
  groups:
    - stratalign-admins

- sub: bar
  name: Bar
  email: bar@example.com
  email_verified: true
  aud: spm-web
  groups:
    - stratalign-users
